spring:
  # datasource
  datasource:
    url: jdbc:mysql://104.224.159.254:3306/aikang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: As_123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    spring.datasource.filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    tomcat:
      initial-size:
  # http
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true   #热部署生效
# mybatis
mybatis:
  type-aliases-package: com.aik.model
  mapper-locations: com/aik/mapper/*Mapper.xml
# tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 80
  context-path: /aik
# JWT
jwt:
  header: Authorization
  secret: as
  expiration: 604800
  tokenHead: "Bearer "
  doctor-sign: "[@doctor@]"
  user-sign: "[@user@]"
# file
file:
# windows
#  upload-root-uri: "C:/Users/as/Pictures/"
# linux
  upload-root-uri: "/usr/soft/file/"
  mapping-root-uri: "/file"
# system
system:
# windows
#  api-uri: "http://localhost/aik"
# linux
  api-uri: "http://104.224.159.254/aik"
# logger
logging:
  level:
    com.aik: DEBUG
# sms
juhe:
  sms:
    api: "http://v.juhe.cn/sms/send"
    appKey: "60c8caf06319012aab075a924ab9f4f1"
    securityCodeTID: 48262
    inviteCodeTID: 48422
  voice:
    api: "http://op.juhe.cn/yuntongxun/voice"
    appKey: "5125ad3ae26b2385cf7f39a84d390c41"
tencent:
  userInfoApi: "https://graph.qq.com/user/get_user_info"
  appId: "1106333845"
  appKey: "jLaGQuiMhC8nnGNr"
wechat:
  userInfoApi: "https://api.weixin.qq.com/sns/userinfo"
  appId: "wx01a226153351b6e3"
  appSecret: "db3f4541e9483a69c700208b5214e9f5"


